# Basic Ubuntu container with tools such as vim, git, python etc.
#this yaml file does not work any more
apiVersion: v1
kind: Pod
metadata:
 name: sfr-pod-wyin
 namespace: sfr-ns-wyin
spec:
 restartPolicy: OnFailure
 volumes:
   - name: sfr-home-pv-wyin
     persistentVolumeClaim:
       claimName: sfr-home-pvc-wyin
   - name: sfr-share-pv-wyin
     persistentVolumeClaim:
       claimName: sfr-share-pvc-wyin
#    - emptyDir:
#      medium: Memory
#      name: dshm
 affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: sfr-node-type
           operator: In
           values:
           - gpu8-512g
 containers:
   - name: wyin
     image: "gcr.io/salesforce-research-internal/yingbo-pytorch"
     command: ["sleep","infinity"]
     volumeMounts:
       - name: sfr-home-pv-wyin
         mountPath: "/export/home"
       - name: sfr-share-pv-wyin
         mountPath: "/export/share"
#        - name: dshm
#          mountPath: /dev/shm
     resources:
       limits:
         nvidia.com/gpu: 8
         cpu: "63"
         memory: 384G
